name: Deploy Blog

on:
  push:
    branches:
      - main # Roda só quando fizer push na main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      # Run tests
      - name: Run tests
        run: yarn test --run
